events {
    worker_connections 1024;
}

http {
    # Evita que o Nginx mostre sua versão em páginas de erro (boa prática de segurança)
    server_tokens off;

    server {
        # A porta interna do container do Nginx
        listen 8080;

        # ----------------------------------------------------
        # Rotas do AUTH-SERVICE
        # ----------------------------------------------------
        location /login { proxy_pass http://auth-service:8080; }
        location /register { proxy_pass http://auth-service:8080; }
        location /refresh { proxy_pass http://auth-service:8080; }
        location /edit-user { proxy_pass http://auth-service:8080; }
        location /delete-user { proxy_pass http://auth-service:8080; }

        # ----------------------------------------------------
        # Rotas de Conflito (/users)
        # Auth e Message usam rotas começando com /users.
        # A regra mais específica vem primeiro!
        # ----------------------------------------------------
        # Vai para o message-service
        location /users/friends { proxy_pass http://message-service:8081; }
        
        # O resto do /users vai para o auth-service (/users, /users/username/...)
        location /users { proxy_pass http://auth-service:8080; }

        # ----------------------------------------------------
        # Rotas do MESSAGE-SERVICE
        # ----------------------------------------------------
        location /messages { proxy_pass http://message-service:8081; }
        location /api/keys { proxy_pass http://message-service:8081; }

        # Configuração Especial para WebSocket
        location /ws-message {
            proxy_pass http://message-service:8081;
            # Para o WebSocket funcionar, o Nginx precisa fazer um Upgrade na conexão HTTP
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # ----------------------------------------------------
        # Rotas do LOG-SERVICE
        # ----------------------------------------------------
        location /logs { proxy_pass http://log-service:8083; }
        
        # Configuração global de Headers que são passados para todos os serviços
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
